name: tmdb_api
description: Dart client-side API package for TMDB.org API (https://www.themoviedb.org/).
version: 1.2.6
# author: Ratakondala Arun<ratakondalaarun@gmail.com>
homepage: https://github.com/RatakondalaArun/tmdb_api.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.13.0
  colorize: ^2.0.0

dev_dependencies:
  test: ^1.14.2
