name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0

      - name: ⏬ Install dependencies
        run: dart pub get

      - name: 🌏 Set Env variables and Run Tests
        env:
          API_V3: ${{ secrets.API_KEY_V3 }}
          API_V4: ${{ secrets.API_KEY_V4 }}
        run: dart test
